CC = arm-linux-gcc
CFLAGS = -Wall -pthread  -g

LIBDIR = lib
BINDIR = bin
OBJDIR = $(BINDIR)/obj
TARGET = $(BINDIR)/ReloadSerial

INCLUDE += 	./\
			./serial\
			./handle\
			./inifile\
			./utils\

SRCDIR +=	./\
			./serial\
			./handle\
			./inifile\
			./utils\

include allrules.mk
