CC = arm-linux-gcc
CFLAGS = -Wall -pthread  -g

LIBDIR = lib
BINDIR = bin
OBJDIR = $(BINDIR)/obj
TARGET = $(BINDIR)/DemoSerial

INCLUDE += 	./\
			./serial\

SRCDIR +=	./\
			./serial\

include allrules.mk
